[package]
name = "log2gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
image = { version = "0.25.5", features = ["png", "jpeg", "pnm"] }
nalgebra = "0.33.2"
